Repository LOG680-gr02-eq11/oxygen-cs-gr02-eq11, pull requests merged in 2023-07, with the labels that each got.

#12 Features/parametrize application
  .github/workflows
  .gitignore
  src/main.py
  src/test_main.py
Labels: bug, Priority: High

#13 Pushing env params Feature to main
  .github/pipelineCI.yaml
  .github/workflows
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  src/main.py
  src/test_main.py
Labels: Priority: High, feature

#14 Features/parametrize application
  .github/workflows
  .github/workflows/main.yml
  requirements.txt
  src/test_main.py
  test/test.py
Labels: Priority: High, feature

#4 Added pipeline.yml file
  .flake8
  .github/workflows/main.yml
  .github/workflows/pipelineCI_revamp.yml
  .idea/.gitignore
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  bandit.yaml
  pipelineCI_Old.yaml
  requirements.txt
  src/main.py
  tests/__init__.py
  tests/test_exemple.py
  tests/test_main.py
Labels: bug, Testing, Priority: High, feature

#15 Merging Develop features to Main Branch & Testing Pipeline configs
  .flake8
  .github/workflows
  .github/workflows/pipelineCI_revamp.yml
  .idea/.gitignore
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  bandit.yaml
  pipelineCI_Old.yaml
  src/main.py
  test/test.py
  tests/__init__.py
  tests/test_exemple.py
  tests/test_main.py
Labels: bug, Testing, Priority: High, feature

#17 Features/ajout ci
  .github/workflows/pipelineCI.yml
  tests/test_exemple.py
Labels: bug, Priority: High

#19 Checking up with Githubs Actions checks to Main
  .github/workflows/pipelineCI.yml
  tests/test_exemple.py
  tests/test_main.py
Labels: bug, Testing, Priority: High, feature

#22 Optimize image docker
  Dockerfile
Labels: Priority: Medium, feature

#23 Optimize the Dockerfile by using requirements textfile instead of pipenv
  Dockerfile
  requirements.txt
Labels: Priority: Medium, feature

#24 Adding oxygen data into our postgresql database
  .DS_Store
  .github/workflows/pipelineCI.yml
  .gitignore
  Pipfile
  Pipfile.lock
  docker-compose.yml
  pytest.ini
  src/.DS_Store
  src/database/db.py
  src/database/models/temperature.py
  src/database/schemas/temperature.py
  src/main.py
  src/service.py
Labels: Priority: Medium, feature

#25 Added a third test for empty testcase
  pipelineCI_Old.yaml
  src/main.py
  tests/test_main.py
Labels: Testing, Priority: Low

#26 Next iteration of changes
  .DS_Store
  .flake8
  .github/workflows/pipelineCI.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  docker-compose.yml
  pipelineCI_Old.yaml
  pytest.ini
  requirements.txt
  src/.DS_Store
  src/database/db.py
  src/database/models/temperature.py
  src/database/schemas/temperature.py
  src/main.py
  src/service.py
  tests/test_main.py
Labels: bug, Testing, Priority: High, feature

#27 Features/optimize image docker
  .dockerignore
  Dockerfile
Labels: Priority: Medium, feature

#28 Optimisation under 40mb
  Dockerfile
Labels: Priority: High, feature

#29 Optimize docker image to be under 40mb
  .dockerignore
  Dockerfile
Labels: Priority: High, feature
